### ISSUE TITLE
Use XML Scheme to have valid xml

### ISSUE THREAD

**Issue by christian-beckmann** [ThePixelDeveloper/Sitemap-v2#11]
http://www.sitemaps.org/protocol.html 

Use the xml scheme to have valid xml for http://www.validome.org/xml/validate/ 

Like 

     <urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

         xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"

         xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"

         xmlns:example="http://www.example.com/schemas/example_schema">

and

     <sitemapindex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

         xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd"

         xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

**Comment by ThePixelDeveloper** [comment]
Thanks for raising this, going to work on this for the next release (which is coming soon, sorry it took so long to integrate).

**Comment by christian-beckmann** [comment]
Thanks this would be great :+1:

**Comment by ThePixelDeveloper** [comment]
Worked on this on the develop (v4) branch you can see here https://github.com/ThePixelDeveloper/Sitemap-v2/tree/develop 

I'll have a release prepared for the end of the week if all goes well.
