### ISSUE TITLE
[Insight] Interfaces names should end with &quot;Interface&quot; - in src/Sitemap/Formatter.php, line 5

### ISSUE THREAD

**Issue by ThePixelDeveloper** [ThePixelDeveloper/Sitemap-v2#7]
**[in src/Sitemap/Formatter.php, line 5](https://github.com/ThePixelDeveloper/Sitemap-v2/blob/master/src/Sitemap/Formatter.php#L5)**

> Interface `Formatter` should be named `FormatterInterface` for better clarity.

```php
<?php

namespace Sitemap;

interface Formatter {

    public function render($sitemaps);

}
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/ed6d56e8-c908-44dc-9154-a8edc8b168bc/analyses/1)_

**Comment by rockymontana** [comment]
I agree
